<a href="https://colab.research.google.com/github/juanfcgarcia/data_analysis_challenge/blob/master/Numpy_Excercises_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import numpy as np
import random

# Numpy Excercises - Session 2

### Exercise 1

Reshape `array1` to 7x3 dimensions.

In [ ]:
array1 = np.arange(0, 21)
print(array1)
array1 = np.reshape(array1, (7, 3))
print(array1)
print(array1[0:3, 0:1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
[[0]
 [3]
 [6]]


### Exercise 2

Reshape `array2` into a 3D array of 3x3x3 dimensions.

In [ ]:
array2 = np.arange(0, 27).reshape(9, 3)
array2 = np.reshape(array2,(3,3,3))
print(array2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### Exercise 3: Reshape vs Resize

reshape and resize both do the same thin. So, what's the difference?

Follow the instructions and find out.


In [ ]:
# Run this cell without changing the code.
array3 = np.arange(0, 9)

array3.reshape((3, 3))
print(array3)

array3.resize((3, 3))
print(array3)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Question: What is the difference between reshape and resize

a = "resize returns a new copy of the array, while reshape changes the original array"
b = "reshape returns a new copy of the array, while resize changes the original array"
c = "both resize and reshape works in the same way with the original array"

Answer: b

### Exercise 4

Concatenate arrays `a`, `b`, and `c`.

In [ ]:
a = np.arange(0, 3)
b = np.arange(3, 6)
c = np.arange(6, 9)

array4 = np.concatenate((a, b, c))
print(array4)

[0 1 2 3 4 5 6 7 8]


### Exercise 5

Concatenate arrays `m1` and `m2` vertically.

In [ ]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array5 = np.concatenate((m1, m2), axis = 0)
print(array5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Exercise 6

Concatenate arrays `m1` and `m2` horizontally.

In [ ]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array6 = np.concatenate((m1, m2), axis = 1)
print(array6)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


### Exercise 7

Get all the cells with value equals to `0` as a list of tuples.


In [ ]:
matrix = np.array([
    [1, 4, 7, 5, 0],
    [0, 2, 9, 0, 1],
    [3, 6, 0, 5, 3],
    [7, 3, 0, 1, 0],
    [3, 6, 1, 0, 4]
])
array7 = np.argwhere(matrix == 0)
array7 = [tuple(i) for i in array7]
print(array7)

[(0, 4), (1, 0), (1, 3), (2, 2), (3, 2), (3, 4), (4, 3)]


### Exercise 8

Check the documentation for `np.diag` and `np.fliplr`. Use them to extract the diagonals arrays for `matrix`.



In [ ]:
diag1 = np.diag(matrix)
print(diag1)

diag2 = np.fliplr(matrix)
print(diag2)

[1 2 0 1 4]
[[0 5 7 4 1]
 [1 0 9 2 0]
 [3 5 0 6 3]
 [0 1 0 3 7]
 [4 0 1 6 3]]


### Exercise 9

Get the values of the 3th column in `matrix` and the values for the 2th row in `matrix`. Both as numpy arrays.


In [ ]:
column = np.array(matrix[:, 2])
print(column)

row = np.array(matrix[1,:])
print(row)

[7 9 0 0 1]
[0 2 9 0 1]


## Exercise 10

Create a new matrix ***x*** from ***a*** and ***m*** with the folowing structure:



```
array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])
```



In [ ]:
a = np.full((3, 1), 5)
m = np.full((3, 4), 4)

x = np.insert(m, 2, a[0], axis = 1)
print(x)

[[4 4 5 4 4]
 [4 4 5 4 4]
 [4 4 5 4 4]]


## Exercise 11

Given a:

```
a = array([[1],
       [1],
       [2],
       [4]])
```

Create a new array **b** with the following structure:

```
np.array([
  [1, 0, 0],
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
])
```
Do you detect the pattern? Which operation do you need to create this structure.?




In [ ]:
#Answer: a contains the positions in which 1 is inserted, the maximum number 
#is the number of columns, also a constains 4 elements so we will have 4 rows
#in this case we will have
# [[1. 0. 0. 0.]
# [1. 0. 0. 0.]
# [0. 1. 0. 0.]
# [0. 0. 0. 1.]]
#now we need delete the column 2 and will have the structure seen above

array = np.array([[1], [1], [2], [4]])
shape = (array.size, arr.max())
b = np.zeros(shape)
rows = np.arange(array.size)

for h in range(len(array)):
    b[h, array[h] - 1] = 1

b = np.delete(b, 2, 1)
print(b)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Challenge, Tic Tac Toe


In [87]:
cell = {
    0: ' ',
    1: 'X',
    2: 'O'
}

winner = False

def print_board():
  print('-------------')
  print(f'| {cell[game[0][0]]} | {cell[game[0][1]]} | {cell[game[0][2]]} |')
  print('-------------')
  print(f'| {cell[game[1][0]]} | {cell[game[1][1]]} | {cell[game[1][2]]} |')
  print('-------------')
  print(f'| {cell[game[2][0]]} | {cell[game[2][1]]} | {cell[game[2][2]]} |')
  print('-------------')

def skynet_move():
  # Select a random empty cell in `game` array and set with value `2`.
  # If no empty cells available, do nothing.
  possibilities = np.argwhere(game == 0)
  if possibilities.size > 0:
    select = possibilities[np.random.randint(0, possibilities.size/2, size = 1)]
    game[select[0][0]][select[0][1]] = 2

def verify_col(game_array):
  for elem in range(0,3):
      inspector = np.array(game_array[:, elem])
      if np.all(inspector == inspector[0]) and inspector[0] != 0:
         return True
    

def verify_row(game_array):
  for elem in range(0,3):
      inspector = np.array(game_array[elem,:])
      if np.all(inspector == inspector[0]) and inspector[0] != 0:
          return True

def verify_diag(diago):
  if np.all(diago == diago[0]) and diago[0] != 0:
          return True

def win_move(player, r, c):
  # Check if the player's move is a win move.
  # A win move meets one of these conditions:
  #   - All values at row `r` are equal to `player`.
  #   - All values at column `c` are equal to `player`.
  #   - All values at main diagonal ((0, 0) to (2, 2)) are equal to  `player`.
  #   - All values at second diagonal ((2, 0) to (0, 2)) are equal to  `player`.
  # Return True if one of the conditions are met, False otherwise.
  state = False
  diag_left = np.diag(game)
  diag_right = np.diag(np.fliplr(game))

  if verify_col(game) or verify_row(game) or verify_diag(diag_left) or verify_diag(diag_right):
      state = True
      winner = True

  return state

def human_move(r, c):
  # Set value `1` at game[r][c] if the cell if empty and return True.
  # If cell is not empty print "Cell is not empty" and return False.
  if game[r][c] == 0:
    game[r][c] = 1
    return True
  else:
    print("Cell is not empty")
    return False

def winner_exists(winner_n):
  # If one of the players has already won the game, return True.
  # Return False otherwise.
  if winner_n:
    return True
  else:
    return False


def is_game_on():
  # This method checks the current status of the game.
  # A game is on if meets one of two conditios:
  #  - There is still available cells.
  #  - There is still no winners.  
  if np.sum(game == 0) > 0 or winner_exists(winner) == False:
    return True
  

In [81]:
# Run this cell to restart the game.

# Create a 3x3 array with zero values.
game = np.zeros((3, 3), dtype = int)
print(game)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [85]:
#@title Tic tac toe controls
#@markdown Select the cell for your next move!.
row_value = "1" #@param ["0", "1", "2"] 
column_value = "0" #@param ["0", "1", "2"]

row = int(row_value)
column = int(column_value)
if(is_game_on()):
  status = human_move(row, column)
  if(win_move(1, row, column)):
    print('Human wins')
  elif(status):
    skynet_move()
    if(win_move(2, row, column)):
      print('Skynet wins')
else:
  print('Game over.')
  
print_board()

Skynet wins
-------------
| O | O | O |
-------------
| X | O | X |
-------------
|   | X | X |
-------------


# Challenge: Basic data analysis

The following numpy array is taken from the a census dataset. Every column in this matrix contains some demografic information. For this exercise You will focus in the following columns:

*   Column[0]: Age
*   Column[1]: workclass
*   Column[3]: education
*   Column[5]: marital-status
*   Column[9]: sex
*   Column[10]: capital-gain

Please find the following information:


*   Age average
*   Types of workclass, education and marital-status
*   How many records are for male
*   How many records are for female
*   How many females are above age of 30
*   Avergage of capital-gain for males
*   Avergage of capital-gain for females







In [ ]:
# First upload file "census.npy" befor running this cell.
with open('/census.npy', 'rb') as f:
  census_data = np.load(f, allow_pickle=True)
print(census_data)
type(census_data)

[[50 ' Self-emp-not-inc' 83311 ... 13 ' United-States' ' <=50K']
 [38 ' Private' 215646 ... 40 ' United-States' ' <=50K']
 [53 ' Private' 234721 ... 40 ' United-States' ' <=50K']
 ...
 [58 ' Private' 151910 ... 40 ' United-States' ' <=50K']
 [22 ' Private' 201490 ... 20 ' United-States' ' <=50K']
 [52 ' Self-emp-inc' 287927 ... 40 ' United-States' ' >50K']]


numpy.ndarray

In [ ]:
#Ave average
print(census_data[:,0])
np.mean(census_data[:,0])

[50 38 53 ... 58 22 52]


38.581633906633904

In [ ]:
#Types of workclass, education and marital-status
print("workclass types:")
print(np.unique(census_data[:,1]))
print("---------------")
print("education types:")
print(np.unique(census_data[:,3]))
print("---------------")
print("marital types:")
print(np.unique(census_data[:,5]))

workclass types:
[' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']
---------------
education types:
[' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']
---------------
marital types:
[' Divorced' ' Married-AF-spouse' ' Married-civ-spouse'
 ' Married-spouse-absent' ' Never-married' ' Separated' ' Widowed']


In [ ]:
#How many records are for male
np.sum(census_data[:,9] == ' Male')

21789

In [ ]:
#How many records are for female
np.sum(census_data[:,9] == ' Female')

10771

In [ ]:
#How many females are above age of 30
census_data[(census_data[:,9] == ' Female') & (census_data[:,0] > 30)][:,0].size

6512

In [ ]:
#Avergage of capital-gain for males
np.mean(census_data[(census_data[:,9] == ' Male')][:,10])

1329.3313139657625

In [ ]:
#Avergage of capital-gain for females
np.mean(census_data[(census_data[:,9] == ' Female')][:,10])

568.4105468387336